server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: administracion-service
          uri: lb://administracion-service
          predicates:
            - Path=/administracion/**
        - id: gestion-service
          uri: lb://gestion-service
          predicates:
            - Path=/gestion/**